/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <assert.h>

#define MAX_VALUE 4000000

int main(int argc, const char * argv[])
{
    uint32_t first = 1;
    uint32_t second = 2;
    uint32_t sum = second;
    
    while (true)
    {
        first = first + second;
        if (first > MAX_VALUE)
        {
            break;
        }
        
        if (first % 2 == 0)
        {
            sum += first;
        }
        
        second = first + second;
        if (second > MAX_VALUE)
        {
            break;
        }
        
        if (second % 2 == 0)
        {
            sum += second;
        }
    }
    
    printf("Sum: %i\n", sum);
    return 0;
}

